# Generated by Django 4.0.4 on 2022-04-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_product_managers_remove_product_p_is_published'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='p_is_published',
            field=models.BooleanField(default=True),
        ),
    ]
