# Generated by Django 4.0.4 on 2022-04-15 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_product_managers_product_p_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_is_published',
        ),
    ]
